language: cpp
dist: trusty

branches:
  only:
    - master

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r/test
#    packages:
#      - g++-7
#      - doxygen
#      - doxygen-doc
#      - doxygen-latex
#      - doxygen-gui
#      - graphviz
#      - cmake
#      - libgtest-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-7 cmake doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
#   update alternatives to use g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1000
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1000
  - sudo update-alternatives --config gcc --skip-auto
  - sudo update-alternatives --config g++ --skip-auto

  # install gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd ..

  # install newer LCOV (apt version outdated and fails for new gcov).
  - sudo wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - sudo tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - which lcov

  # Install coverals gem for uploading coverage to coveralls.
  - sudo gem install coveralls-lcov

  # go to build dir
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - lcov --version
  - gcov --version
  - g++  --version
  - ls -l

script:
  # release
  - mkdir build-release && cd build-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF ..
  - make
  - cd ..
  # coverage
  - mkdir build-coverage && cd build-coverage
  - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_EXAMPLES=OFF ..
  - make coverage
  - cd ..
  # docs
  - cd docs
  - doxygen Doxyfile

after_success:
  - cd "${TRAVIS_BUILD_DIR}"/build-coverage
  - ls -l
  - lcov --list coverage_out.info.cleaned  # Show test report in travis log.
  - coveralls-lcov coverage_out.info.cleaned  # uploads to coveralls

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/html
  github-token: ${GITHUB_API_TOKEN}
  on:
    branch: master